Cleaning up the project structure.
PawseySC/pawsey-spack-config pull request #145
Opened 2022-11-24 07:27 UTC by dipietrantonio

As a first refactoring step, we should delete some unused folders. In primis, Zeus and Magnus directories should be removed as those systems are no longer here (for those wondering, note that those files will still be present in the git history, so they are not actually lost).

I also suggest to remove the deprecated directory, probably there to act as an archive, but git handles that part for us.

2022-11-30 11:03 UTC, dipietrantonio commented
@pelahi @ddeeptimahanti I have implemented most of the changes we discussed during the last meeting.

Tomorrow I will create a subdirectory for secondary scripts, and will go ahead and test shpc. Deva or I will create a 'setonix_datamover' system.

2022-12-07 02:02 UTC, ddeeptimahanti requested changes
${script_dir} is undefined in scripts/post_refresh_modules.sh 
please see if other scripts using this variable are also affected

2023-01-06 02:51 UTC, pelahi approved these changes

2023-01-06 02:54 UTC, ddeeptimahanti approved these changes

2023-01-06 03:43 UTC, merged