Auto populate packages.yaml with ROCm externals
PawseySC/pawsey-spack-config pull request #167
Opened 2023-06-20 07:47 UTC by dipietrantonio

To easily allow for multiple ROCm versions in  `packages.yaml` of Setonix, I created the `generate_rocm_externals.sh` script, called by `install_spack.sh`, which generates the externals for ROCm given a list of ROCm versions and paths set in the `settings.sh` file.

2023-06-20 07:49 UTC, dipietrantonio commented on scripts/generate_rocm_externals.sh
> +echo """      - spec: $package@$rocm_ver
Notice the indentation to match the one in the packages.yaml file

2023-06-20 08:25 UTC, pelahi requested changes

2023-06-20 08:25 UTC, pelahi commented on scripts/generate_rocm_externals.sh
I think it would be good to have some way of checking if a rocm package is install or not and account for that when updating the packages.yaml.

2023-06-20 08:25 UTC, pelahi commented on systems/setonix/configs/site/packages.yaml
The packages.yaml without rocm packages could be called a more specific name like packages.yaml.base and this gets updated and added to the spack configuration as packages.yaml.

2023-06-21 09:19 UTC, dipietrantonio commented on scripts/generate_rocm_externals.sh
Done, in the last commit. Here is an example of running the updated script on Setonix

```
  rocm-smi-lib:
      externals:
      - spec: rocm-smi-lib@5.0.2
        prefix: /opt/rocm-5.0.2
      - spec: rocm-smi-lib@5.4.3
        prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev1
      buildable: false

  rocwmma:
      externals:
      - spec: rocwmma@5.4.3
        prefix: /software/setonix/2022.11/pawsey/software/rocm/rocm-5.4.3rev1
      buildable: false

  rocm-openmp-extras:
      externals:
      - spec: rocm-openmp-extras@5.0.2
        prefix: /opt/rocm-5.0.2
      buildable: false
```

My question now is, should buildable be false?

2023-06-21 09:24 UTC, dipietrantonio commented on systems/setonix/configs/site/packages.yaml
This would mark the file as "incomplete", which makes sense. However, that would complicate the "install_spack" script , adding more code to handle the cases where the script is and is not executed for Setonix. I don't think it is worth it.

2023-06-21 11:31 UTC, marcodelapierre commented on scripts/generate_rocm_externals.sh
considering how important and also delicate to build the ROCm stack is, buildable = false could be a good idea. other points of view?

2023-06-22 02:06 UTC, dipietrantonio commented on scripts/generate_rocm_externals.sh
I agree with you. If users encounter errors because of missing packages, we should handle them ourselves. However, all the main ROCm packages are present, so I doubt it will happen in practice.

2023-06-22 02:22 UTC, pelahi commented on systems/setonix/configs/site/packages.yaml
How do we track packages that have failed to install? If currently we just set the package to not be listed but still be `buildable: false` the error might not be informative. Still, this is likely beyond the scope of this update and should just be considered for a future update.

2023-06-22 02:22 UTC, pelahi approved these changes

2023-06-22 03:05 UTC, ddeeptimahanti approved these changes
Looks good to me!

2023-06-22 03:08 UTC, merged