Building petsc with and without complex
PawseySC/pawsey-spack-config pull request #235
Opened 2023-09-29 05:48 UTC by ddeeptimahanti

2023-09-29 06:09 UTC, pelahi requested changes

2023-09-29 06:09 UTC, pelahi commented on systems/setonix/environments/num_libs/spack.yaml
Is there a reason for removing the explicit variant for petsc? Why not keep them all except complex?

2023-09-29 06:31 UTC, ddeeptimahanti commented on systems/setonix/environments/num_libs/spack.yaml
just wanted to avoid repeating  +fftw ~trilinos +hwloc +openmp ~cuda twice for both versions so I kept it in the matrix.

2023-09-29 07:03 UTC, pelahi approved these changes

2023-10-09 06:02 UTC, dipietrantonio approved these changes

2023-10-09 06:21 UTC, ilkhomab approved these changes

2023-10-09 07:01 UTC, merged