Adds recipes WSClean and all its dependencies
PawseySC/pawsey-spack-config pull request #273
Opened 2024-06-06 10:18 UTC by dipietrantonio

This is a work-in-progress to build wsclean and dependencies on Setonix (and Garrawarla).

2024-06-10 02:29 UTC, d3v-null commented
Hey @dipietrantonio could you please rebase this onto main (which has mwalib et. al.) ? thanks

2024-06-10 05:19 UTC, d3v-null commented
aoflagger needs the `+date_time` variant of `boost`

2024-06-10 16:40 UTC, dipietrantonio commented
@d3v-null  Done :)

2024-06-13 08:43 UTC, dipietrantonio commented
@d3v-null confirmed these work on Setonix, and so do I. I also tested them in a stand-alone spack environment. Some earlier version of everybeam might not work correctly, but the latest versions do and that is what is actually needed for the Garrawarla migration.

2024-06-17 01:42 UTC, pelahi requested changes

2024-06-17 01:42 UTC, pelahi commented on repo/packages/aoflagger/as.patch
Should we worry that these changes were necessary? This seems like the code would never compile if it really needed these changes. @dipietrantonio or perhpas @d3v-null can comment.

2024-06-17 01:42 UTC, pelahi commented on repo/packages/aoflagger/package.py
Shouldn't the hdf5 dependency just have `hdf5@1.10: +cxx ~mpi api=v110`

2024-06-17 01:42 UTC, pelahi commented on repo/packages/birli/package.py
I am puzzled by the curl dependency. If it's because cfitsio has it as a dependency then birli shouldn't have this as a dependency. @d3v-null can you comment?

2024-06-17 01:42 UTC, pelahi commented on repo/packages/casacore/package.py
We should also ensure that the build flag `-DENABLE_TABLELOCKING=NO` is passed as this does not play nice with luster.

2024-06-17 02:03 UTC, dipietrantonio commented on repo/packages/aoflagger/as.patch
I think they compile with an older, more permissive GCC, but not with GCC 12.2.0 on Setonix.

2024-06-17 02:04 UTC, dipietrantonio commented on repo/packages/aoflagger/package.py
Good point

2024-06-17 02:14 UTC, d3v-null commented on repo/packages/birli/package.py
try removing it and see what happens when you reinstall and run Birli.
I'm pretty sure cfitsio is built without the `--disable-curl` flag which means libcurl needs to be available at runtime in order to load libcfitsio.

2024-06-17 02:35 UTC, pelahi commented on repo/packages/birli/package.py
I don't this as when I check cfitsio, I see `spack find -lvd cfitsio`
```
-- linux-sles15-zen3 / gcc@12.2.0 -------------------------------
rvvpkwk cfitsio@4.3.0+bzip2+shared build_system=autotools
w4dnqgs     bzip2@1.0.8~debug~pic+shared build_system=generic
4nv6m5b         diffutils@3.9 build_system=autotools
ipnfwll             libiconv@1.17 build_system=autotools libs=shared,static
wpby2ud     curl@7.79.1~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl
yrxsuab     gmake@4.4.1~guile build_system=generic
```
So it does pull in curl. Perhaps this was the case before?

2024-06-17 02:37 UTC, pelahi commented on repo/packages/aoflagger/as.patch
Is there a gcc that would allow you build without `using namespace std;`? I'll take your word for it but unless it is a really old gcc, this should have failed write away. Can you make a PR on the source repo for aoflagger? They should fix this.

2024-06-17 02:38 UTC, d3v-null commented on repo/packages/birli/package.py
ok, I think at some point in previous spack recipes, system cfitsio would be used, in which case it wouldn't see that curl was needed. Maybe this has been fixed.

2024-06-17 03:15 UTC, dipietrantonio commented on repo/packages/aoflagger/as.patch
The patch is for the version 3.2.0, 3.4 has a fix for it.

2024-06-17 03:18 UTC, dipietrantonio commented on repo/packages/casacore/package.py
I think you had already done some work for it
```
        if spec.satisfies('+adios2'):
            args.append(self.define('ENABLE_TABLELOCKING', False))
```

2024-06-18 01:22 UTC, pelahi commented on repo/packages/casacore/package.py
We should do this regardless and so should add a build variant. Will see if I can do this today.

2024-06-18 01:34 UTC, dipietrantonio commented on repo/packages/casacore/package.py
I can do this myself.

2024-06-18 05:30 UTC, d3v-null commented on repo/repo.yaml
you probably don't want to change this @dipietrantonio

2024-06-18 07:10 UTC, dipietrantonio commented
@ilkhomab @pelahi I addressed all the comments. @pelahi I added the 'tablelocking' variant to casacore (`default=False`)

2024-06-18 07:13 UTC, dipietrantonio commented on repo/packages/birli/package.py
> +    version("0.10.0", tag="v0.8.0")
Thanks for reviewing and catching the error!

2024-06-18 07:38 UTC, pelahi commented on repo/packages/dedisp/package.py
This package is missing a description.

2024-06-18 07:39 UTC, pelahi requested changes

2024-06-18 07:39 UTC, pelahi commented on repo/packages/wsclean/package.py
Need to add the description back.

2024-06-18 17:46 UTC, dipietrantonio commented on repo/packages/wsclean/package.py
Well spotted, done.

2024-06-18 17:47 UTC, dipietrantonio commented on repo/packages/dedisp/package.py
This package has been committed by mistake, I removed it altogether.

2024-06-19 14:07 UTC, pelahi approved these changes

2024-06-20 00:57 UTC, ddeeptimahanti approved these changes

2024-06-20 01:12 UTC, merged