Feature/maali garrawarla
PawseySC/pawsey-spack-config pull request #72
Opened 2022-02-16 07:35 UTC by pelahi

A first attempt at having a garrawarla specific spack configs.

2022-02-17 05:10 UTC, pelahi commented
Currently seems fine based on tests by Harrison. The only issue might be an update to the modules path. However, this is likely best handled manually to ensure that modules follow the flat hierarchy that exists on garrawarla.

2022-02-22 02:59 UTC, marcodelapierre commented
Going to add comments here and there in the code, where relevant :)

2022-02-22 03:01 UTC, marcodelapierre commented on examples/garrawarla/configs/compilers.yaml
> +    spec: gcc@10.1.0
Just noting that the default GCC compiler on Garrawarla is currently 8.3.0.
For instance, OpenMPI on Garrawarla is currently not built with 10.1.0.
If users and us are happy with using 10.1.0 for the Spack stack, then no further action here.

2022-02-22 03:04 UTC, marcodelapierre commented on examples/garrawarla/configs/config.yaml
> +    - $spack/var/spack/stage
for these 4 service directories, consider adding `$USER` in the path, similar to what we're doing on Setonix, as it seemed more robust, e.g.:
```
$spack/var/spack/$USER/stage
```

2022-02-22 03:06 UTC, marcodelapierre commented on examples/garrawarla/configs/modules.yaml
> +  enable::
by looking at the Spack modules yaml, I think this enable::lmod should be deleted,
as the good one is further down, at the beginning of the `default:` section

2022-02-22 03:07 UTC, marcodelapierre commented on examples/garrawarla/configs/config.yaml
> +    root: /pawsey/mwa_sles12sp4/spack/software/
edit to `mwa_sles12sp5`

2022-02-22 03:08 UTC, marcodelapierre commented on examples/garrawarla/configs/modules.yaml
> +      lmod: /pawsey/mwa_sles12sp5/modulefiles/
if not willing to mix with the non-Spack stack, change this to:
```
/pawsey/mwa_sles12sp5/spack/modulefiles/
```

2022-02-22 03:10 UTC, marcodelapierre commented on examples/garrawarla/configs/packages.yaml
> +    compiler: [gcc@8.3.0, gcc@4.8.5]
ensure the list of compilers is consistent with `compilers.yaml`, e.g. right now it's `8.3.0` in packages, and `10.1.0` in compilers

2022-02-22 03:12 UTC, marcodelapierre commented on examples/garrawarla/configs/packages.yaml
> +      write: group
`write: user` probably better, it will restrict to maali/spack (whichever will be)

2022-02-22 03:16 UTC, marcodelapierre commented on examples/garrawarla/configs/config.yaml
> +    - /astro/pawsey0001/maali/pawsey-spack-config/examples/garrawarla/templates
maybe rename `maali` to `$USER`, as MarkO suggested they might just rename the `maali` user to `spack` everywhere

2022-02-22 03:16 UTC, marcodelapierre commented on examples/garrawarla/configs/repos.yaml
> +- /astro/pawsey0001/maali/pawsey-spack-config/setonix/repo_setonix
maybe rename `maali` to `$USER`, as MarkO suggested they might just rename the `maali` user to `spack` everywhere

2022-02-22 03:18 UTC, marcodelapierre commented on examples/garrawarla/README.md
> +## Topaz prototype deployment
README and TEST seem just drafted from Topaz, skipping them

2022-02-22 03:18 UTC, marcodelapierre commented on examples/garrawarla/setup/README.md
> +# Scripts and modules to deploy key tools on Garrawarla
skipping the whole `setup/` directory, seems drafted

2022-02-22 03:19 UTC, marcodelapierre commented on examples/garrawarla/templates/modules/modulefile.lua
> +load("{{ module |replace("astro-applications/", "") |replace("bio-applications/", "") |replace("py-keras-applications/", "pawsey-temporary-string/") |replace("applications/", "") |replace("pawsey-tem
here and in the line above, i.e. 71 and 73, does `devel/` refers to developer tool packages?
If so, maybe consider using `developer/`, or `developers/`.

2022-02-22 03:24 UTC, marcodelapierre requested changes
Great work, thanks @pelahi !
It seems like I have made a lot of comments, but it's all small changes (if approved).

As a general comment, I think it is increasingly likely we're going to use Spack to deploy a fraction of the software stack on both Garrawarla and Topaz, and I think it's a good thing.
We only need to draw appropriate boundaries in terms of user expectations.
For instance, I would suggest to consider not supporting Spack user installations on these two clusters for now (unlike Setonix), and flag our system-wide one as experimental/exploratory.
Also, minor thing, when you're happy with a garrawarla production setup feel free to move it up one level in the directory tree, same as setonix.

2022-05-06 06:44 UTC, merged